### ISSUE TITLE
In the latest release after I cleared cache I can not login

### ISSUE THREAD

**Issue by electro89** [deso-protocol/frontend#181]
In the latest release after I cleared cache I can not login. Seems that local variable for API is not setting, had to manually add a variable lastLocalNodeV2 and defined it. Is this normal or error in my browser?

**Comment by tsheaff** [comment]
@electro89 can you specify a few things so that this  is debuggable:

* What data did you clear from the browser? Cookies, local storage etc.
* Was there an error you were getting in the JS console?
* What was the user experience when you did try to log in? Were you logging in with your seed?
* Which browser and OS?
* Are you able to reliably reproduce this issue still?

**Comment by maebeam** [comment]
@electro89 I'm going to close this since we haven't heard any reports of this issue in a few months. Please reopen if you like.
