### ISSUE TITLE
Implement middle click to open new tab on Bitclout.com

### ISSUE THREAD

**Issue by balajis** [deso-protocol/frontend#259]
Problem: right now you can't easily open multiple tabs on the Bitclout.com web interface by middle clicking the timestamp.

Solution: enable this behavior, just like Twitter.

**Comment by tijno** [comment]
Whats the macOs equivalent ? right or cmd click i think.

i would love this !!

**Comment by AdityaChaudhary0005** [comment]
As far I understand this problem, Balajis want the timeStamp as a link button so that one can open the link in new tab
![Screenshot from 2021-07-10 14-27-16](https://user-images.githubusercontent.com/55331140/125157883-1ab97e80-e18b-11eb-828b-506214a8b830.png)
right now there is no way to open post in new tab

**Comment by chafreaky** [comment]
The behavior is mixed when for example clicking on a url in a post. The click will fire 2 events:
- one that will open the clicked link in a new tab
- another that will also open the current clicked post in the current page

I think this can be solved by `e.preventDefault()` on link clicks.

**Comment by maebeam** [comment]
Fixing this behavior would be a massive win

**Comment by AdityaChaudhary0005** [comment]
so @chafreaky you doing PR ? I tried myself but couldn't find the best possible solution.

**Comment by chafreaky** [comment]
Angular is not my strong suit but I can give it a try.

**Comment by jagath-ft** [comment]
I found the solution and it is working, the only issue that i notice here is "Page Title" is not getting updated in new tab, it is showing default title as "Welcome to BitClout" instead of eg: "balajis on Bitclout".
Working on to update page title dynamically on the fly, will keep you guys updated..

![image](https://user-images.githubusercontent.com/58214552/125430885-9fa064fd-741f-43ce-948c-145223658b68.png)

**Comment by jagathks** [comment]
I found the solution and it is working, the only issue that i notice here is "Page Title" is not getting updated in new tab, it is showing default title as "Welcome to BitClout" instead of eg: "balajis on Bitclout".
Working on to update page title dynamically on the fly, will keep you guys updated..

![image](https://user-images.githubusercontent.com/17216156/125435901-100884bb-ac7d-4f98-b37d-a4af24a67590.png)

**Comment by AdityaChaudhary0005** [comment]
Great work @jagathks !

What's your BitClout handle? Time to follow another gem!

**Comment by maebeam** [comment]
Timestamp middle click has been fixed in #278 but it would be great to allow command + clicking (or windows equivalent) anywhere on the post.

**Comment by jagathks** [comment]
Sound's good, will try to add this.
I can somewhere correlate this with issue #299. Will try to add both the features.

**Comment by jagathks** [comment]
I think this can be closed now, PR submitted for #299 with one more update.

**Comment by jagathks** [comment]
@maebeam @balajis why this issue is still open?
